# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_auto_20180326_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='location',
            new_name='place',
        ),
    ]
